
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.My_SP_KEY }}
      # - run: npm ci
      # - run: npx semantic-release

      - name: Set versions
        id: app-versions
        run: |
          APP_VER=`jq '.version' package.json`
          echo '::set-output name=APP_VERSION::$APP_VER'
        

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic   # Need an `id` for output variables
      #   with:
      #     extra_plugins: |
      #       @semantic-release/changelog@3.0.0
      #       @semantic-release/git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push event to other repo
        if: steps.semantic.outputs.new_release_published == 'true'
        # uses: convictional/trigger-workflow-and-wait@v1.3.0
        # with:
        #   owner: bilalshahzad139
        #   repo: target-repo
        #   github_token: ${{ secrets.PAT_TOKEN }}
        #   workflow_file_name: blank.yml
        #   ref: main
        #   wait_workflow: false
        #   inputs: '{"event_type":"event_type","client_payload":{"id":"1"}}'
        run: |
          echo ${{ steps.app-versions.outputs.APP_VERSION }}
          curl -XPOST -u "bilalshahzad139:${{secrets.PAT_TOKEN}}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/bilalshahzad139/target-repo/dispatches -d '{"event_type":"event_type","client_payload":{"app_version":"${{ steps.app-versions.outputs.APP_VERSION }}"}}'

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: |
      #     echo $IS_PUBLISH_VERSION
      #     echo ${{env.IS_PUBLISH_VERSION}}
      
      - uses: hmarr/debug-action@v2

      # - name: push event to other repo
      #   run: curl -XPOST -u "bilalshahzad139:${{secrets.PAT_TOKEN}}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/bilalshahzad139/target-repo/dispatches -d '{"event_type":"event_type","client_payload":{"id":"1"}}'
